accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from candidate import views as candidate_views
from employers import views as employer_views
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('profile/settings/', views.settings, name="settings"),

    # create resume
    path('resume/new/', views.AddResumeView.as_view(), name='add-resume'),
    # access resume
    path('resume/<int:pk>', views.ResumeView.as_view(), name='resume'),
    # update resume 
    path('resume/<int:pk>/update/', views.UpdateResumeView.as_view(), name='resume-update'),
    # delete resume
    path('resume/<int:pk>/delete/', views.DeleteResumeView.as_view(), name='resume-delete'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from jobposts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('', include('accounts.urls')),
    path('blog/', include('blogy.urls')),
    path('', include('jobposts.urls')),

    # messages
    path('messages/', include('postman.urls', namespace='postman')),

    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobposts/urls.py
from django.urls import path
from . import views
from candidate import views as candidate_views
from employers import views as employer_views

app_name = "jobposts"
urlpatterns = [
    path('', views.index, name="index_blog"),
    path('testvue/', views.testvue2, name="testvue"),

    #get job post detail
    path('job/<int:pk>', views.job_detail, name="job-detail"),

    # create job post
    path('job/new/', views.JobCreateView.as_view(), name="job-create"),

    # update job post
    path('job/<int:pk>/update', views.JobUpdateView.as_view(), name="job-update"),

    # delete job post
    path('job/<int:pk>/delete', views.JobDeleteView.as_view(), name="job-delete"),

    # bookmark, unbookmark job posts
    path('<int:id>/bookmark/', candidate_views.JobBookmarkView.as_view(), name="job-bookmark"),
    path('<int:id>/unbookmark/', candidate_views.JobUnbookmarkView.as_view(), name="job-unbookmark"),

    # bookmark, unbookmark resumes 
    path('resume/<int:id>/bookmark/', employer_views.ResumeBookmarkView.as_view(), name="resume-bookmark"),
    path('resume/<int:id>/unbookmark/', employer_views.ResumeUnBookmarkView.as_view(), name="resume-unbookmark"),


    # list of all job posts
    path('browse/', views.job_list, name="job-list"),
    path('categories/', views.categories, name="categories"),

    # search
    path('search/', views.search, name="search"),

    # browse resumes
    path('browse/resumes/', views.browse_resumes, name="browse-resumes"),
    # search resumes
    path('search/resumes/', views.search_resumes, name="search-resumes"),

    # browse remote jobs
    path('browse/remotes/', views.remote_job_list, name="browse-remotes")

]

jobposts/forms.py
from django import forms
from . import models 
from tinymce.widgets import TinyMCE
from crispy_forms.helper import FormHelper


from . import models

class DateInput(forms.DateInput):
    input_type = 'date'


class JobCreateForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 10, 'rows': 10}))

    class Meta:
        model = models.Job
        fields = ('title','description','location','job_type','category',
                    'originally_posted_url','closing','salary','apply_url','years_of_exp')
        widgets = {'closing':DateInput(),
                    'category': forms.CheckboxSelectMultiple()
                }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['location'].widget.attrs['placeholder'] = 'e.g Tallinn, Tartu'
        self.helper = FormHelper()
        self.helper.form_show_labels = False 

jobposts/views.py
from django.shortcuts import render, get_object_or_404, Http404, HttpResponseRedirect, reverse, redirect, HttpResponse
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.decorators import method_decorator
from django.db.models import Count
from django.db.models import Q
from django.template.loader import render_to_string
from django.core.serializers.json import DjangoJSONEncoder
from django.urls import resolve
import requests
from datetime import datetime

from django.http import JsonResponse
import json

from . import models as models
from . import forms
from blogy import models as blog_models
from candidate import models as candidate_models
from . import utils
from accounts import decorators

import json
import random

###########################
#
#   TEST ONLY
#
###########################
def testvue(request):
    names = ("bob", "dan", "jack", "lizzy", "susan")
    data = list(models.Job.objects.values().order_by('-created_at'))[:4]

    items = []
    for i in range(100):
        items.append({
            "name": random.choice(names),
            "age": random.randint(20,80),
            "url": "https://example.com",
        })

    context = {
        'items_json': json.dumps(items),
        'data_json': json.dumps(data, cls=DjangoJSONEncoder),
    }

    return render(request, 'test_vue.html', context)

def testvue2(request):
    jobs = models.Job.objects.filter(is_active=True)
    
    context = {
        'jobs':jobs
    }

    return render(request, 'test_vue2.html', context)


################################
#
# END TESTS
#
################################

def index(request):
    latest = models.Job.objects.order_by('-created_at')[:7]
    queryset = models.Job.objects.all()
    count_active_jobs = models.Job.objects.filter(closing__gt=datetime.now()).count()
    count_total_jobs = models.Job.objects.all().count()
    featured = models.Job.objects.filter(featured=True).order_by('-created_at')[:3]
    latest_blog_posts = blog_models.Post.objects.all()[:3]
    categories = models.Category.objects.all()

    categories = utils.get_category_count(0,10)

    response = requests.get('https://quotesondesign.com/wp-json/wp/v2/posts/?orderby=rand')
    items = []
    for item in response.json():
        items.append({
            "quote": item['content']['rendered']
        })
        print('{}'.format(item['content']['rendered']))
    

    context = {
        'latest':latest,
        'object_list':queryset,
        'count_active_jobs':count_active_jobs,
        'count_total_jobs':count_total_jobs,
        'featured':featured,
        'latest_posts':latest_blog_posts,
        'categories':categories,
        'items':items
    }

    return render(request, 'index.html', context)

def job_detail(request, pk):
    template_name = "jobposts/job-detail.html"
    job = get_object_or_404(models.Job, id=pk)

    job_query = models.Job.objects.filter(id=pk)

    hourly = utils.get_hourly(job_query)

    context = {
        'job':job,
        'hourly':hourly
    }

    return render(request, template_name, context)


def job_list(request):
    template_name = "jobposts/browse-jobs.html"

    jobs = models.Job.objects.filter(closing__gt=datetime.now()).order_by('-created_at')
    total_full_time_jobs = jobs.filter(job_type="1").count()
    total_part_time_jobs = jobs.filter(job_type="2").count()

    total_jobs = total_full_time_jobs + total_part_time_jobs

    categories = models.Category.objects.all()

    base_jobs = models.Job.objects.filter(closing__gt=datetime.now())

    job_by_salary_desc = base_jobs.order_by('-salary')
    job_by_salary_asc = base_jobs.order_by('salary')
    job_by_oldest = base_jobs.order_by('created_at')
    job_by_expiring = base_jobs.order_by('-closing')

    value = request.POST.get('sort')
    if value in ('-salary','salary','created_at','-created_at','-expiring'):
        data = {
            'value': value,
        }
        return JsonResponse(data)
    
    value = request.POST.get('check_val')
    if value in ('check-1','check-2','check-3'):
        data = {
            'checked_value':value
        }
        return JsonResponse(data)

    jobs = utils.pagination(request, jobs, 8)
    job_by_oldest = utils.pagination(request, job_by_oldest, 8)
    job_by_salary_desc = utils.pagination(request, job_by_salary_desc, 8)
    job_by_salary_asc = utils.pagination(request, job_by_salary_asc, 8)
    job_by_expiring = utils.pagination(request, job_by_expiring, 8)

    if request.user.is_authenticated:
        context = {
            'jobs':jobs,
            'total_full_time_jobs':total_full_time_jobs,
            'total_part_time_jobs':total_part_time_jobs,
            'categories':categories,
            'job_by_salary_desc': job_by_salary_desc,
            'job_by_salary_asc': job_by_salary_asc,
            'job_by_oldest': job_by_oldest,
            'total_jobs': total_jobs,
            'job_by_expiring': job_by_expiring,
        }
        return render(request, template_name, context)
    else: 
        context = {
                'jobs':jobs,
                'total_full_time_jobs':total_full_time_jobs,
                'total_part_time_jobs':total_part_time_jobs,
                'categories':categories,
                'job_by_salary_desc': job_by_salary_desc,
                'job_by_salary_asc': job_by_salary_asc,
                'job_by_oldest': job_by_oldest,
                'total_jobs': total_jobs,
                'job_by_expiring': job_by_expiring,
            }
        return render(request, template_name, context)

    
    

@method_decorator(decorators.employer_required, name='dispatch')
class JobCreateView(LoginRequiredMixin, CreateView):
    model = models.Job
    form_class = forms.JobCreateForm
    template_name = 'jobposts/add-job_form.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            print(form.errors.as_data())
            return redirect("jobposts:job-create")

    def form_valid(self, form):
        form.instance.company_name = self.request.user
        return super().form_valid(form)



class JobUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Job
    form_class = forms.JobCreateForm
    template_name = 'jobposts/add-job_form.html'

    def form_valid(self, form):
        form.instance.company_name = self.request.user
        return super().form_valid(form)
    
    # prevent users to edit any posts
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.company_name:
            return True
        return False

class JobDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Job
    success_url = "/"
    template_name = "jobposts/confirm-job-delete.html"

    # prevent users to edit any posts
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.company_name:
            return True
        return False


def search(request):
    categories = models.Category.objects.all()
    jobs = models.Job.objects.filter(closing__gt=datetime.now()).order_by('-created_at')

    base_jobs = models.Job.objects.filter(closing__gt=datetime.now())

    job_by_salary_desc = base_jobs.order_by('-salary')
    job_by_salary_asc = base_jobs.order_by('salary')
    job_by_oldest = base_jobs.order_by('created_at')

    total_full_time_jobs = jobs.filter(job_type="1").count()
    total_part_time_jobs = jobs.filter(job_type="2").count()

    found_job_count = 0

    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            jobs = jobs.filter(Q(title__icontains=keywords) | Q(description__icontains=keywords))

    if 'city' in request.GET:
        city = request.POST.get('city')
        if city: 
            jobs = jobs.filter(location__iexact=city)

    # checking for get request from ajax to filter categories if there is only one element in array
    if 'category_val' in request.GET:
        category_val = request.GET['category_val']

        if category_val:
            jobs = jobs.filter(category__title__iexact=category_val)
            found_job_count = jobs.count()

        # checking for get request from ajax to filter categories if there is 2 elements if array
        if 'category_val2' in request.GET:
            category_val = request.GET['category_val']
            category_val2 = request.GET['category_val2']
            
            if category_val2:
                jobs = jobs.filter(category__title__iexact=category_val).filter(category__title__iexact=category_val2)
                found_job_count = jobs.count()

        if 'category_val3' in request.GET:
            category_val = request.GET['category_val']
            category_val2 = request.GET['category_val2']
            category_val3 = request.GET['category_val3']
            
            if category_val3:
                jobs = jobs.filter(category__title__iexact=category_val).filter(category__title__iexact=category_val2)\
                                    .filter(category__title__iexact=category_val3)
                found_job_count = jobs.count()
        
        if 'category_val4' in request.GET:
            category_val = request.GET['category_val']
            category_val2 = request.GET['category_val2']
            category_val3 = request.GET['category_val3']
            category_val4 = request.GET['category_val4']
            
            if category_val4:
                jobs = jobs.filter(category__title__iexact=category_val).filter(category__title__iexact=category_val2)\
                                    .filter(category__title__iexact=category_val3).filter(category__title__iexact=category_val4)

templates/jobposts/browse-categories.html
{% extends 'base.html' %}

{% block title %}| Categories {% endblock title %}

{% block content %}

<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background: url(https://estonianworld.com/wp-content/uploads/2018/02/P%C3%A4rnu-Rene-K%C3%BC%C3%BCsvek-1-1024x683.jpg); background-attachment: fixed; width:100%">
	<div class="container-own">
		<div class="ten columns">
			<h2>All Categories</h2>
		</div>

		<div class="six columns">
			<a href="add-job.html" class="button">Post a Job, It’s Free!</a>
		</div>

	</div>
</div>


<!-- Content
================================================== -->
<div id="categories">
	<!-- Categories Group -->
	<div class="categories-group">
		<div class="container-own">
			<div class="four columns"><h4>Web, Software & IT</h4></div>
			<div class="four columns">
				<ul>
				{% for cat in categories1 %}
					<li><a href="{% url 'jobposts:search' %}?category_val={{ cat.category__title }}">{{ cat.category__title }}</a></li>
				{% endfor %}
				</ul>
			</div>
			<div class="four columns">
				<ul>
				{% for cat in categories2 %}
					<li><a href="{% url 'jobposts:search' %}?category_val={{ cat.category__title }}">{{ cat.category__title }}</a></li>
				{% endfor %}
				</ul>
			</div>
			<div class="four columns">
				<ul>
				{% for cat in categories3 %}
					<li><a href="{% url 'jobposts:search' %}?category_val={{ cat.category__title }}">{{ cat.category__title }}</a></li>
				{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/jobposts/browse-resumes.html
{% extends 'base.html' %}

{% block title %}  Resumes {% endblock %}

{% block content %}

<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container-own">
		<div class="ten columns">
			{% url 'jobposts:search-resumes' as sr %}
			{% if sr in request.path %}
			<span>We found {{ resumes|length }} resumes!</span>
			{% else %}
			<span>There is {{ resumes|length }} resume(s) uploaded on our website</span>
			{% endif %}
			<h2>Web, Software & IT</h2>
		</div>

		{% if user.is_authenticated and user.is_candidate %}
		<div class="six columns">
			<a href="{% url 'accounts:add-resume' %}" class="button">Post a Resume, It’s Free!</a>
		</div>
		{% endif %}

	</div>
</div>


<div class="container-own">
	{% if messages|length < 2 %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
</div>

<div style="padding-top:10px;"></div>

<!-- Content
================================================== -->
<div class="container-own">
	<!-- Recent Jobs -->
	<div class="eleven columns">
	<div class="padding-right">
		
		<form action="{% url 'jobposts:search-resumes' %}" class="list-search">
			<button><i class="fa fa-search"></i></button>
			<input name="keywords" type="text" placeholder="job title, keywords or company name" value="{{ values.keywords }}" />
			<div class="clearfix"></div>
		</form>

		<ul class="resumes-list">
			{% for resume in resumes %}
				<li>
					<img src="{{ resume.owner.candidateprofile.image.url }}" alt="">
						<div class="resumes-list-content">
							{% include 'jobposts/browse-resumes_script.html' %}

							<a style="text-decoration:none;" href="{% url 'accounts:resume' resume.id %}">
								<h4>{{ resume.owner.first_name }} {{ resume.owner.last_name }}<span>{{ resume.professional_title }}</span></h4>
							</a>	
							<br/>
							<span style="padding: 2px;"><i class="fa fa-map-marker"></i> {{ resume.location }}</span>
							<span><i class="fa fa-birthday-cake"></i> {{ resume.owner.candidateprofile.date_of_birth }}</span>
							<p>{{ resume.description|truncatewords_html:8|safe }}</p>

							<div class="skills">
								{% for skill in resume.owner.candidateprofile.skills.all %}
									<span>{{ skill }}</span>
								{% endfor %}
							</div>
						</div>
					<div class="clearfix"></div>
				</li>
			
			{% endfor %}
		</ul>
					
	</div>
	</div>


	<!-- Widgets -->
	<div class="five columns">

		<!-- Sort by -->
		<div class="widget">
			<h4>Sort by</h4>

			<!-- Select -->
			<select data-placeholder="Choose Category" class="chosen-select-no-single">
				<option selected="selected" value="recent">Relevance</option>
				<option value="">Hourly Rate – Highest First</option>
				<option value="">Hourly Rate – Lowest First</option>
			</select>

		</div>

		<!-- Skills -->
		<div class="widget">
			<h4>Skills</h4>

			<!-- Select -->
				<select data-placeholder="Select Skills" class="chosen-select" multiple>
					{% for cat in categories %}
						<option value="">{{ cat.title }}</option>
					{% endfor %}
				</select>
				<div class="margin-top-15"></div>
				<button class="button">Filter</button>
		</div>

		<!-- Location -->
		<div class="widget">
			<h4>Location (not impemented)</h4>
			<form action="#" method="get">
				<input type="text" placeholder="State / Province" value=""/>
				<input type="text" placeholder="City" value=""/>

				<input type="text" class="miles" placeholder="Miles" value=""/>
				<label for="zip-code" class="from">from</label>
				<input type="text" id="zip-code" class="zip-code" placeholder="Zip-Code" value=""/><br>

				<button class="button">Filter</button>
			</form>
		</div>

	</div>
	<!-- Widgets / End -->
</div>

<script>

var outside = null;

$(document).on("DOMNodeInserted", function(e) {
	var li = $(this)
	var found = li.find('.search-choice span').text();
	var found_arr = found.split(/(?=[A-Z])/)
	if (found !== "") {
		outside = found_arr
	} 
});

$(document).ready(function() {
	$("button[class='button']").click(function() {
		for (let i = 0; i < outside.length; i++){
			if (i != 0) {
				outside[i] = "&?category_val"+(i+1)+"="+outside[i] 
			} 
		}
		loc = outside.join('') 
		loc = "?category_val=" + loc
		window.location.replace("{% url 'jobposts:search-resumes' %}" + loc)
		$.ajax({
			type:'GET',
			url:'{% url "jobposts:search-resumes" %}',
			data:{
				category_val:outside[0],
				category_val2:outside[1],
				category_val3:outside[2],
				category_val4:outside[3],
			},
    	});
	});
});

</script>

{% endblock %}

templates/jobposts/browse-resumes_script.html
{% load employer_tags %}

{% if user.is_authenticated and user.is_employer %}
    <div class="bookmark">
        {% is_resume_bookmarked resume.id request.user as is_resume_booked %}
            {% if is_resume_booked %}
                <a style=""href="{{ resume.get_unbookmark_url }}">
                    <img style="height:40px; width:50px; margin-left: 0px;"id="bookmarked-{{ resume.id }}" src="https://img.icons8.com/ios-filled/50/000000/bookmark-ribbon.png"/>
                </a>
            {% else %}
                <a href="{{ resume.get_bookmark_url }}">
                    <img style="height:40px; width:50px; margin-left: 0px;" id="bookmarked-{{ resume.id }}" src="https://img.icons8.com/ios/50/000000/bookmark-ribbon.png"/>
                </a>
            {% endif %}

            <!-- jQuery to change bookmark icon on hover depending on the job id -->
            <script>
                $(document).ready(function(){
                    $("img[id^='bookmarked-{{ resume.id }}']").on({
                        {% if is_resume_booked %}
                            mouseenter: function() {
                                $(this).attr("src","https://img.icons8.com/ios/50/000000/bookmark-ribbon.png");
                            },
                            mouseleave: function() {
                                $(this).attr("src","https://img.icons8.com/ios-filled/50/000000/bookmark-ribbon.png");
                            }
                        {% else %}
                            mouseenter: function() {
                                $(this).attr("src","https://img.icons8.com/ios-filled/50/000000/bookmark-ribbon.png");
                            },
                            mouseleave: function() {
                                $(this).attr("src","https://img.icons8.com/ios/50/000000/bookmark-ribbon.png");
                            }
                        {% endif %}
                    });	
                });
            </script>
    </div>

{% endif %}
  

templates/jobposts/confirm-job-delete.html
{% extends "base.html" %}

{% block title %}| Confirm Delete {% endblock title %}

{% block content %}


    <div class="container-own">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Hey {{ request.user.username }}!</legend>
                <h2>Are you sure you want to delete your following post: "{{ object.title }}"
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'jobposts:job-detail' object.id %}">Cancel</a>
            </div>
            
        </form>
    </div>
    <div style="margin-bottom:300px;"></div>

{% endblock content %}

templates/jobposts/job-detail.html
{% extends "base.html" %}

{% load static %}
{% load accounts_tags %}
{% load candidate_tags %}

{% block title %}| {{ job.title }} {% endblock title %}

{% block content %}

{% get_dominant_color job.company_name.company.user as dominant_col %}
{% is_bookmarked job.id request.user as is_booked %}

<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container-own">
		<div class="ten columns">
			<span>IT / Software</span>
			<h2>{{ job.title }}{% if job.job_type == "1" %} <span class="full-time">Full-Time</span>{%else%} <span class="part-time">Part-Time</span>{% endif %}</h2>
		</div>

		{% if not job.company_name.company.user.id == request.user.id and user.is_candidate %}
			{% if is_booked %}
				<div class="six columns">
					<a href="{{ job.get_unbookmark_url }}" class="button dark"><i class="fa fa-star"></i> Delete Bookmark</a>
				</div>
			{% else %}
				<div class="six columns">
					<a href="{{ job.get_bookmark_url }}" class="button dark"><i class="fa fa-star-o"></i> Bookmark This Job</a>
				</div>
			{% endif %}
		{% endif  %}

	</div>
</div>


<!-- Content
================================================== -->
<div class="container-own">
	
	<!-- Recent Jobs -->
	<div class="eleven columns">
	<div class="padding-right">
		
		<!-- Company Info -->
		<div class="company-info" style="height: 150px;">
			<img src="{{ job.company_name.company.company_thumb.url }}" alt="">
			<div class="content">
				<div style="display:inline-block; width: 650px;">
					<h4 style="display:inline-block; margin-right:10px;">{{ job.company_name.company.company_name }}</h4>{% if dominant_col %}<span class="dot" style="background-color:{{ dominant_col }}"></span>{% endif %}
					{% if job.company_name.company.user.id == request.user.id %}
					<div class="dropdown" style="float:right; ">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:#8B8D7E;">
							Update Post
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item" href="{% url 'jobposts:job-update' job.id %}">Update</a>
							<a class="dropdown-item" href="{% url 'jobposts:job-delete' job.id %}">Delete</a>
						</div>
					</div>
				{% endif %}
				
				
				</div>
				<div>
				<span><a href="{{ job.company_name.company.company_website }}"><i class="fa fa-link"></i> Website</a></span>
				{% if job.company_name.company.twitter_link %}
				<span><a href="{{ job.company_name.company.twitter_link }}"><i class="fa fa-twitter"></i> @something</a></span>
				{% endif %}
				</div>
			</div>
			
			<div class="clearfix"></div>
		</div>

		{{ job.description|safe }}

	</div>
	</div>


	<!-- Widgets -->
	<div class="five columns">

		<!-- Sort by -->
		<div class="widget">
			<h4>Overview</h4>

			<div class="job-overview">
				
				<ul>
					<li>
						<i class="fa fa-map-marker" style="color:#302A30;"></i>
						<div>
							<strong>Location:</strong>
                            {% for loc in job.location.all %}
							<span>{{ loc.title }}</span>
                            {% endfor %}
						</div>
					</li>
					<li>
						<i class="fa fa-user" style="color:#302A30;"></i>
						<div>
							<strong>Job Title:</strong>
							<span>{{ job.title }}</span>
						</div>
					</li>
					<li>
						<i class="fa fa-clock-o" style="color:#302A30;"></i>
						<div>
							<strong>Hours:</strong>
							{% if job.job_type == "1" %}
							<span>40h / week</span>
							{% else %}
							<span>< 20h / week</span>
							{% endif %}
						</div>
					</li>
					{% if hourly > 1 %}
					<li>
						<i class="fa fa-money" style="color:#302A30;"></i>
						<div>
							<strong>Rate:</strong>
							<span>{{ hourly }} € / hour</span>
						</div>
					</li>
					{% endif %}
					<li>
						<i class="fa fa-gears" style="color:#302A30;"></i>
						<div>
							<strong>Tech required:</strong>
							<div style="margin-bottom:15px;"></div>
								{% for stack in job.category.all %}
									<img src="{{ stack.category_thumb.url }}" style="width:30px;display:inline-block;margin: 10px;">
								{% endfor %}
						</div>
					</li>
					{% if job.closing %}
					<li>
						<i class="fa fa-caret-square-o-right" style="color:#302A30;"></i>
						<div>
							<strong>Closing:</strong>
							<div style="margin-bottom:15px;"></div>
								<span>{{ job.closing }}</span>
						</div>
					</li>
					{% endif %}
				</ul>


				<a href="{{ job.apply_url }}" class="popup-with-zoom-anim button">Apply For This Job</a>

				<div id="small-dialog" class="zoom-anim-dialog mfp-hide apply-popup">
					<div class="small-dialog-headline">
						<h2>Apply For This Job</h2>
					</div>

					<div class="small-dialog-content">
						<form action="#" method="get" >
							<input type="text" placeholder="Full Name" value=""/>
							<input type="text" placeholder="Email Address" value=""/>
							<textarea placeholder="Your message / cover letter sent to the employer"></textarea>

							<!-- Upload CV -->
							<div class="upload-info"><strong>Upload your CV (optional)</strong> <span>Max. file size: 5MB</span></div>
							<div class="clearfix"></div>

							<label class="upload-btn">
							    <input type="file" multiple />
							    <i class="fa fa-upload"></i> Browse
							</label>
							<span class="fake-input">No file selected</span>

							<div class="divider"></div>

							<button class="send">Send Application</button>
						</form>
					</div>
					
				</div>

			</div>

		</div>

	</div>
	<!-- Widgets / End -->


</div>

<div style="margin-bottom:40px;"></div>

{% endblock content %}
<!-- Footer
================================================== -->