accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from candidate import views as candidate_views
from employers import views as employer_views
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('profile/settings/', views.settings, name="settings"),

    # create resume
    path('resume/new/', views.AddResumeView.as_view(), name='add-resume'),
    # access resume
    path('resume/<int:pk>', views.ResumeView.as_view(), name='resume'),
    # update resume 
    path('resume/<int:pk>/update/', views.UpdateResumeView.as_view(), name='resume-update'),
    # delete resume
    path('resume/<int:pk>/delete/', views.DeleteResumeView.as_view(), name='resume-delete'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from jobposts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('', include('accounts.urls')),
    path('blog/', include('blogy.urls')),
    path('', include('jobposts.urls')),

    # messages
    path('messages/', include('postman.urls', namespace='postman')),

    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogy/urls.py
from django.urls import path
from . import views

app_name = "blogy"
urlpatterns = [
    path('', views.index_blog, name="index_blog"),
    path('post/<int:pk>', views.post_detail, name="post_detail"),
    path('results/', views.blog_search, name="search")
]

jobposts/urls.py
from django.urls import path
from . import views
from candidate import views as candidate_views
from employers import views as employer_views

app_name = "jobposts"
urlpatterns = [
    path('', views.index, name="index_blog"),
    path('testvue/', views.testvue2, name="testvue"),

    #get job post detail
    path('job/<int:pk>', views.job_detail, name="job-detail"),

    # create job post
    path('job/new/', views.JobCreateView.as_view(), name="job-create"),

    # update job post
    path('job/<int:pk>/update', views.JobUpdateView.as_view(), name="job-update"),

    # delete job post
    path('job/<int:pk>/delete', views.JobDeleteView.as_view(), name="job-delete"),

    # bookmark, unbookmark job posts
    path('<int:id>/bookmark/', candidate_views.JobBookmarkView.as_view(), name="job-bookmark"),
    path('<int:id>/unbookmark/', candidate_views.JobUnbookmarkView.as_view(), name="job-unbookmark"),

    # bookmark, unbookmark resumes 
    path('resume/<int:id>/bookmark/', employer_views.ResumeBookmarkView.as_view(), name="resume-bookmark"),
    path('resume/<int:id>/unbookmark/', employer_views.ResumeUnBookmarkView.as_view(), name="resume-unbookmark"),


    # list of all job posts
    path('browse/', views.job_list, name="job-list"),
    path('categories/', views.categories, name="categories"),

    # search
    path('search/', views.search, name="search"),

    # browse resumes
    path('browse/resumes/', views.browse_resumes, name="browse-resumes"),
    # search resumes
    path('search/resumes/', views.search_resumes, name="search-resumes"),

    # browse remote jobs
    path('browse/remotes/', views.remote_job_list, name="browse-remotes")

]

templates/header.html
{% load static %}

<!-- Header
================================================== -->
<header style="box-shadow: 2px 2px 7px;">
<div class="container-own">
	<div class="sixteen columns">
	
		<!-- Logo -->
		<div id="logo">
			<h1><a href="{% url 'index' %}"><img src="https://logosolusa.com/wp-content/uploads/parser/Random-Logo-1.png" style="width:100px; margin-top:16px;" alt="Logo" /></a></h1>
		</div>

		<!-- Menu -->
		<nav id="navigation" class="menu">
			<ul id="responsive">

				{% url 'index' as ind %}
				{% if request.path == ind %}
					<li><a href="{% url 'index' %}" id="current" style="box-shadow: 2px 2px 2px #3C717F;">Home</a>
				{% else %}
					<li><a href="{% url 'index' %}">Home</a></li>
				{% endif %}

				{% url 'jobposts:job-list' as list %}
					<li><a href="{% url 'jobposts:job-list' %}" {%if request.path == list %}id="current" style="box-shadow: 2px 2px 2px #3C717F;"{%else%}{%endif%}>Browse Jobs</a></li>
				{% url 'jobposts:browse-resumes' as br %}	
					<li><a href="{% url 'jobposts:browse-resumes' %}" {%if request.path == br %}id="current" style="box-shadow: 2px 2px 2px #3C717F;"{%else%}{%endif%}>Browse Resumes</a></li>
				{% url 'jobposts:browse-remotes' as bre %}	
					<li><a href="{% url 'jobposts:browse-remotes' %}" {%if request.path == bre %}id="current" style="box-shadow: 2px 2px 2px #3C717F;"{%else%}{%endif%}>Browse Remotes</a></li>

				{% if user.is_employer and not user.is_candidate %}

					{% url 'jobposts:job-create' as jc %}
					<li><a href="{% url 'jobposts:job-create' %}" {% if request.path == jc %}id="current" style="box-shadow: 2px 2px 2px #3C717F;"{%else%}{%endif%}>Post Job</a></li>

				{% endif %}

				{% url 'blogy:index_blog' as bindex %}
				{% if request.path == bindex or '/blog/post/' in request.get_full_path %}
					<li><a href="{% url 'blogy:index_blog' %}" id="current" style="box-shadow: 2px 2px 2px #3C717F;">Blog</a></li>
				{% else %}
					<li><a href="{% url 'blogy:index_blog' %}">Blog</a></li>
				{% endif %}
			</ul>

			<ul class="float-right">
			{% if user.is_authenticated %}
				
				<div class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="padding: 0px; display: inline-flex; color: white;" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

						{% if user.is_employer %}
							{% with dominant=request.user.company.dominant_color_in_model %}
								<img class="rounded-circle" src="{{ user.company.company_thumb.url }}" style="width:40px; border:solid #505050 1.3px; box-shadow: 2px 2px {% if dominant %}{{ dominant }}{% endif %}" alt=""/>
							{% endwith %}
						{% endif %}

						{% if user.is_candidate %}
							{% with dominant=request.user.candidateprofile.dominant_color_in_model %}
								<img class="rounded-circle" src="{{ user.candidateprofile.image.url }}" style="width:40px; border:solid #505050 1.3px; box-shadow: 2px 2px {% if dominant %}{{ dominant }}{% endif %}" alt=""/>	
							{% endwith %}
						{% endif %}
						
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
						<a class="dropdown-item" href="{% url 'accounts:settings'%}">Settings</a>
						<a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
					</div>
				</div>
				

			{% else %}
				<li><a href="{% url 'accounts:register' %}" {% if 'register' in request.path %}id="current"{%else%}{%endif%}><i class="fa fa-user"></i> Register</a></li>
				<li><a href="{% url 'accounts:login' %}" {% if 'login' in request.path%}id="current"{%else%}{%endif%}><i class="fa fa-lock"></i> Log In</a></li>
			{% endif %}
			</ul>

		</nav>

		<!-- Navigation -->
		<div id="mobile-navigation">
			<a href="#menu" class="menu-trigger"><i class="fa fa-reorder"></i> Menu</a>
		</div>

	</div>
</div>
</header>
<div class="clearfix"></div>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block title %} | HOME {% endblock %}

<!-- Header
================================================== -->

{% block content %}

{% load customtags %}

<!-- Banner
================================================== -->
<div id="banner" style="background: url(https://yonseiuicscribe.com/wp-content/uploads/2019/05/Estonia_1920x1080.jpg); background-attachment: fixed; width:100%; background-repeat: no-repeat; background-size:cover;">
	<div class="container-own">
		<div class="sixteen columns">
			
			<div class="search-container">

				<!-- Form -->
				<h2 style="border: solid; width: 18%; text-align: center; box-shadow: 2px 2px #877C7D;">Find job</h2>
				<form action="{% url 'jobposts:search' %}">
					<input name="keywords" type="text" class="ico-01" placeholder="job title, keywords or company name" value=""/>
					<input name="city" type="text" class="ico-02" placeholder="city" value=""/>
					<button style="box-shadow: 2px 2px #877C7D;"><i class="fa fa-search"></i></button>
				</form>

				<!-- Browse Jobs -->
				<div class="browse-jobs">
					Browse job offers by <a href="{% url 'jobposts:categories'%}"> category</a> or <a href="#">location</a>
				</div>
				
				<!-- Announce -->
				<div class="announce">
					Find the best job on the estonian market! <br/>
					Over <strong>{{ count_total_jobs }}</strong> job offers have been published in our portal!
				</div>

			</div>

		</div>
	</div>
</div>



<!-- Content
================================================== -->

<div class="margin-bottom-55"></div>

<div class="container-own">
	<div class="sixteen columns" style="margin-bottom:30px;">
		<h3 class="margin-bottom-25 underlined">Popular Categories</h3>
		{% for cat in categories %}
				<div style="max-width: 18rem; box-shadow: 2px 2px #877C7D;; display:inline-block; margin: 10px; border: solid 1px;">
				<a href="{% url 'jobposts:search' %}?category_val={{ cat.category__title }}">
					<div class="card-body text-dark" style="display:inline-block;vertical-align:top;">
					{% get_image cat.category__id as get_img %}
					{% for img in get_img %}
						<img src="{{ img.category_thumb.url }}" style="width:30px">
					{% endfor %}
					</div>
					<div style="display:inline-block; padding: 20px; color:black;">
						<div style="font-size: larger;">
							{{ cat.category__title }}							
						</div>
					</div>
				</a>
				</div>
		{% endfor %}	
		</div>
		
		<a href="{% url 'jobposts:categories' %}" class="button centered" style="margin-top:30px;">Browse All Categories</a>
	</div>
</div>

<div class="margin-bottom-55"></div>

<div class="container-own">
	
	<!-- Recent Jobs -->
		<div class="eleven columns">
			<div class="padding-right">
				<div class="">
					<h3 class="margin-bottom-25 underlined">Latest Jobs</h3>
				</div>
				<ul class="job-list">

					{% for job in latest %}
					<li class="highlighted"><a href="{% url 'jobposts:job-detail' job.id %}" style="text-decoration:none;"> <!-- Add absolute url -->
						<img src="{{ job.company_name.company.company_thumb.url }}" style="width:50px;" alt="">
						<div class="job-list-content">
							<h4>{{ job.title }} 
							{% if job.job_type == '1' %}
							<span class="full-time">Full time</span>
							{% endif %}
							{% if job.job_type == '2' %}
							<span class="part-time">Part-Time</span></h4>
							{% endif %}
							</h4>
							<div class="job-icons">

								<span><i class="fa fa-briefcase"></i>{{ job.company_name.company.company_name }}</span>

								{% for loc in job.location.all %}
								<span><i class="fa fa-map-marker"></i> {{ loc }}</span>
								{% endfor %}
							</div>
						</div>
						</a>
						<div class="clearfix"></div>
					</li>
					{% endfor %}
				</ul>

				<a href="{% url 'jobposts:job-list' %}" class="button centered" style="margin-top:30px;"><i class="fa fa-plus-circle"></i>Show More Jobs</a> <!-- Add /jobs link -->
				<div class="margin-bottom-55"></div>
		</div>
		</div>
		<!-- Job Spotlight -->
		<div class="five columns">
			<h3 class="margin-bottom-5 underlined">Job Spotlight</h3>

			<!-- Navigation -->
			<div class="showbiz-navigation">
				<div id="showbiz_left_1" class="sb-navigation-left"><i class="fa fa-angle-left"></i></div>
				<div id="showbiz_right_1" class="sb-navigation-right"><i class="fa fa-angle-right"></i></div>
			</div>
			<div class="clearfix"></div>
			
			<!-- Showbiz Container -->
			<div id="job-spotlight" class="showbiz-container">
				<div class="showbiz" data-left="#showbiz_left_1" data-right="#showbiz_right_1" data-play="#showbiz_play_1" >
					<div class="overflowholder">

						<ul>
							{% for post in featured %}
							<li>
								<div class="job-spotlight" style="box-shadow: 2px 2px #877C7D;">
									<a href="{% url 'jobposts:job-detail' post.id %}" style="text-decoration:none;"><h4 style="font-size: larger;">{{ post.title }}{% if post.job_type == '1' %} <span class="full-time">Full-Time</span>{%else%} <span class="part-time">Part-Time</span>{%endif%}</h4></a>
									<span><i class="fa fa-briefcase"></i> {{ post.company_name.company.company_name }}</span>
									{% for loc in post.location.all %}
									<span><i class="fa fa-map-marker"></i> {{ loc }}</span>
									{% endfor %}
									<br/>
									<span><i class="fa fa-money"></i> {{ post.salary }}€ / month</span>
									<div>
									{{ post.description|truncatewords_html:36|safe }}
									</div>
									<a href="{{ post.apply_url }}" class="button">Apply For This Job</a>
								</div>
							</li>
							{% endfor %}
						</ul>
						
						<div class="clearfix"></div>

					</div>
					<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>


<!-- Testimonials -->
<div id="testimonials">
	<!-- Slider -->
	<div class="container">
		<div class="sixteen columns">
			<div class="testimonials-slider">
			</div>
		</div>
	</div>
</div>

<!-- Recent Posts -->
<div class="container-own">
	<div class="sixteen columns">
		<h3 class="margin-bottom-25 underlined">Recent Blog Posts</h3>
	</div>

	{% for bp in latest_posts %}
	<div class="one-third column">

		<!-- Post #1 -->
		<div class="recent-post">
			<div class="recent-post-img"><a href=""><img src="{{ bp.thumbnail.url }}" alt="" style="clip: rect(0px,30px,200px,0px);"></a><div class="hover-icon"></div></div>
			<a href="{% url 'blogy:post_detail' bp.id %}" style="text-decoration:none;"><h4>{{ bp.title }}</h4></a>
			<div class="meta-tags">
				<span>{{ bp.timestamp|timesince }} ago</span>
				<span><span class="material-icons" style="font-size:14px">forum</span>{{ bp.comment_count }}</span>
			</div>
			<p>{{ bp.content|safe|truncatechars:9 }}</p>
			<a href="{% url 'blogy:post_detail' bp.id %}" class="button">Read More</a>
		</div>

	</div>
	{% endfor %}


</div>

{% endblock content %}


templates/register.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}

{% block content %}

<div class="eleven columns">
        <div class="bg-white">
            <div class="container-fluid p-0">
                <div class="row d-flex align-items-center no-gutters vh-100">
                    <div class="col-12 col-sm-5 col-lg-6 order-sm-2 h-100 image-side bg-primary"> <img src="https://kaptainkennytravel.com/wp-content/uploads/2017/07/IMG_9854-1-1080x1440.jpg" style="height: 100%; width:fit-content;"class="img-fluid img-cover" alt="" /> 
                    
                    </div>
                    <div class="col-12 col-sm-7 col-lg-6 order-sm-1 position-relative p-4">
                        <div class="row d-flex align-items-center flex-column content-box h-100 p-sm-4">
                         
                            <div class="col-lg-7 col-md-8 col-12">

                                <div class="">

                                    <div class="my-account">
                                
                                        <ul class="tabs-nav">
                                            <li class=""><a href="#tab1">Candidate</a></li>
                                            <li><a href="#tab2">Employer</a></li>
                                        </ul>
                                
                                        <div class="tabs-container">
                                
                                                <!-- Register -->
                                                <div class="tab-content" id="tab1" style="display: none;">
                                
                                                    <h3 class="margin-bottom-10 margin-top-10">Register as a candidate</h3>
                                
                                                    <form method="POST" class="register">
                                                        {% csrf_token %}
                                                        {{ form_candidate|crispy }}
                                                                    
                                                        <p class="lost_password">
                                                            <a href="{% url 'accounts:login' %}" >Already have account?</a>
                                                        </p>
                                                        <p class="form-row">
                                                            <input type="submit" class="button" name="register-candidate" value="Register" />
                                                        </p>
                                                        
                                                    </form>
                                                </div>
                                
                                                <div class="tab-content" id="tab2" style="display: none;">
                                
                                                    <h3 class="margin-bottom-10 margin-top-10">Register as an employer</h3>
                                
                                                    <form method="POST" class="register">
                                                        {% csrf_token %}
                                                        {{ form_employer|crispy }}
                                                                    
                                                        <p class="lost_password">
                                                            <a href="{% url 'accounts:register' %}" >Already have account?</a>
                                                        </p>
                                                        <p class="form-row">
                                                            <input type="submit" class="button" name="register-employer" value="Register" />
                                                        </p>
                                                        
                                                    </form>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                                
                             
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/scripts.html
{% load static %}

{% load crispy_forms_tags %}

<script src="{% static 'scripts/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'scripts/custom.js' %}"></script>
<script src="{% static 'scripts/jquery.superfish.js' %}"></script>
<script src="{% static 'scripts/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'scripts/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'scripts/jquery.themepunch.showbizpro.min.js' %}"></script>
<script src="{% static 'scripts/jquery.flexslider-min.js' %}"></script>
<script src="{% static 'scripts/chosen.jquery.min.js' %}"></script>
<script src="{% static 'scripts/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'scripts/waypoints.min.js' %}"></script>
<script src="{% static 'scripts/jquery.counterup.min.js' %}"></script>
<script src="{% static 'scripts/jquery.jpanelmenu.js' %}"></script>
<script src="{% static 'scripts/stacktable.js' %}"></script>
<script type="text/javascript" src="{% static 'js/backgroundChange.js' %}">

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

<script type="text/javascript" src="{% static 'js/scroll/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scroll/jquery.waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scroll/infinite.min.js' %}"></script>


<script>

  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });

</script>

<!-- Infinite scrolling -->
<script>
  var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {
    },
    offset: 'bottom-in-view',

    onBeforePageLoad: function () {
    $('.spinner-border').show();
    },
    onAfterPageLoad: function () {
    $('.spinner-border').hide();
    }

  });
</script>

<!-- Hiding other job divs before filtering -->
<script>

$(document).ready(function() {
  $('#job-list-salary-highest').hide();
  $('#job-list-salary-lowest').hide();
  $('#job-list-oldest').hide();
  $('#job-list-type-fulltime').hide();
  $('#job-list-type-parttime').hide();
  $('#job-list-expiring').hide()
}); 

</script>

<!-- Sort by  -->
<script>

$(document).ready(function() {
 $('#drop').change(function() {
        var val1 = $('#drop option:selected').val();
        console.log(val1);
        $('#job-list').hide();
        $.ajax({
          type:'POST',
          url:'{% url "jobposts:job-list" %}',
          data:{
              sort:$('#drop option:selected').val(),
        },
        dataType: 'json',
        success: function(data){
          if (data.value == '-salary') {
            console.log("success");
            $("div[id^='job-list']").hide()
            $('#job-list-salary-highest').show()
          } 
          else if (data.value == 'salary') {
            console.log("success")
            $("div[id^='job-list']").hide()
            $('#job-list-salary-lowest').show()
          } 
          else if (data.value == 'created_at') {
            console.log("success")
            $("div[id^='job-list']").hide();
            $('#job-list-oldest').show();
          } 
          else if (data.value == '-created_at') {
            console.log("success")
            $("div[id^='job-list']").hide();
            $('#job-list').show();
          } 
          else if (data.value == '-expiring') {
            $("div[id^='job-list']").hide();
            $('#job-list-expiring').show();
          }
        }
    });
 });
});

</script>

<!-- Display job depending on checked value, e.g full-time, part-time -->
<script>

$(document).ready(function() {
  $("input[name=check]").change(function() {
    console.log("checked");
    val1 = $(this).val();
    $.ajax({
          type:'POST',
          url:'{% url "jobposts:job-list" %}',
          data:{
              check_val:val1,
        },
        dataType: 'json',
        success: function(data) {
          if (data.checked_value == 'check-2') {
            $("div[id^='job-list']").hide();
            $('#job-list-type-fulltime').show();
            $("input[value^=check]").prop("checked",false);
            $(`input[value^=${data.checked_value}]`).prop("checked",true);
          }
          else if (data.checked_value == 'check-3') {
            $("div[id^='job-list']").hide();
            $('#job-list-type-parttime').show();
            $("input[value^=check]").prop("checked",false);
            $(`input[value^=${data.checked_value}]`).prop("checked",true);
          }
          else if (data.checked_value == 'check-1') {
            $("div[id^='job-list']").hide();
            $('#job-list').show();
            $("input[value^=check]").prop("checked",false);
            $(`input[value^=${data.checked_value}]`).prop("checked",true);
          }
        }
    });
  });
});

</script>

<script>

$(document).ready(function() {
  if(window.location.href.indexOf("&byoldest") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-oldest").show();
      $('#drop').val('created_at')
  } 
  else if (window.location.href.indexOf("&byexpiring") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-expiring").show();
      $('#drop').val('-expiring')
  }
  else if (window.location.href.indexOf("&byasc") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-salary-lowest").show();
      $('#drop').val('salary')
  }
  else if (window.location.href.indexOf("&bydesc") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-salary-highest").show();
      $('#drop').val('-salary')
  }
  else if (window.location.href.indexOf("&byfulltime") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-type-fulltime").show();
  }
  else if (window.location.href.indexOf("&byparttime") > -1) {
      $("div[id^='job-list']").hide();
      $("#job-list-type-parttime").show();
  }

});

</script>

<script>

if (localStorage.getItem("url_storage_new")) {
    list_for_url = JSON.parse(localStorage.getItem("url_storage_new"));
    list_for_django = JSON.parse(localStorage.getItem("django_storage_new"))
} else {
    // No data, start with an empty array
    list_for_url = ['?'];
    list_for_django = [];
}

if (window.location.pathname == "/search/" || window.location.pathname == "/browse/") {
  localStorage.removeItem("url_storage_new");
  localStorage.removeItem("django_storage_new");
}

$(document).ready(function() {
  $("input[name=category-title]").change(function() {
    val1 = $(this).val();
    if (list_for_django.includes(val1)){
      index = list_for_django.indexOf(val1);
      if (index > -1) {
        list_for_url.splice(index + 1, 1);
        list_for_django.splice(index, 1)
     }
    }
    else {
      if (list_for_url.length < 2) {
        list_for_url.push("category_val=" + val1 + "&");
        list_for_django.push(val1);
      } else {
        list_for_url.push("category_val"+ (list_for_url.length) + "=" + val1 + "&");
        list_for_django.push(val1);
      }
    }

    localStorage.setItem("url_storage_new", JSON.stringify(list_for_url));
    localStorage.setItem("django_storage_new", JSON.stringify(list_for_django));

    // Reordering list because it's messing up if you take the second item off out of 3 items for example
    // it would then display val= and val=3 therefore display an error in django because there is a gap
    for (let i = 0; i < list_for_url.length; i++){
        if (i != 0) {
          loc = list_for_url[i].replace(/[0-9]/g, i); 
          list_for_url[i] = loc;
        }
    }

    loc = list_for_url.join('') 

    window.location.replace("{% url 'jobposts:search' %}" + loc)
    
    $.ajax({
      type:'GET',
      url:'{% url "jobposts:search" %}',
      data:{
          category_val:list_for_django[0],
          category_val2:list_for_django[1],
          category_val3:list_for_django[2],
          category_val4:list_for_django[3],
          category_val5:list_for_django[4],
          category_val6:list_for_django[5],
        },
    });
  });
});

</script>

<script>

const $dropdown = $(".dropdown");
const $dropdownToggle = $(".dropdown-toggle");
const $dropdownMenu = $(".dropdown-menu");
const showClass = "show";

$(window).on("load resize", function() {
  if (this.matchMedia("(min-width: 768px)").matches) {
    $dropdown.hover(
      function() {
        const $this = $(this);
        $this.addClass(showClass);
        $this.find($dropdownMenu).addClass(showClass);
      },
      function() {
        const $this = $(this);
        $this.removeClass(showClass);
        $this.find($dropdownToggle).attr("aria-expanded", "false");
        $this.find($dropdownMenu).removeClass(showClass);
      }
    );
  } else {
    $dropdown.off("mouseenter mouseleave");
  }
});

</script>

<!-- fades the alert messages -->
<script>

setTimeout(fade_out, 2000);

function fade_out() {
  $("div[class^='alert']").fadeOut().empty();
}

</script>