accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from candidate import views as candidate_views
from employers import views as employer_views
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('profile/settings/', views.settings, name="settings"),

    # create resume
    path('resume/new/', views.AddResumeView.as_view(), name='add-resume'),
    # access resume
    path('resume/<int:pk>', views.ResumeView.as_view(), name='resume'),
    # update resume 
    path('resume/<int:pk>/update/', views.UpdateResumeView.as_view(), name='resume-update'),
    # delete resume
    path('resume/<int:pk>/delete/', views.DeleteResumeView.as_view(), name='resume-delete'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from jobposts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('', include('accounts.urls')),
    path('blog/', include('blogy.urls')),
    path('', include('jobposts.urls')),

    # messages
    path('messages/', include('postman.urls', namespace='postman')),

    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candidate/forms.py
from django import forms 
from django.conf import settings
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm
from tinymce.widgets import TinyMCE

from . import models

class DateInput(forms.DateInput):
    input_type = 'date'
    

class CandidateRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email', 'password1','password2']
    
    def save(self):
        user = super().save(commit=False)
        user.is_candidate = True 
        user.save()
        candidate = models.CandidateProfile.objects.create(user=user)
        return user


class ResumeForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 10, 'rows': 10}))

    class Meta:
        model = models.CandidateResume
        fields = ['name','email','professional_title','location','description',

                    'url_name','url_url',
                    'second_url_name','second_url_url',

                    'education_school_name','education_education_major','education_start_date',
                    'education_end_date','education_notes',

                    'second_education_school_name','second_education_education_major','second_education_start_date',
                    'second_education_end_date','second_education_notes',

                    'experience_employer','experience_job_title','experience_start_date',
                    'experience_end_date','experience_notes',

                    'second_experience_employer','second_experience_job_title','second_experience_start_date',
                    'second_experience_end_date','second_experience_notes'
                ]


        widgets =  {'education_start_date': DateInput(),
                    'education_end_date': DateInput(),
                    'experience_start_date': DateInput(),
                    'experience_end_date': DateInput(),
                    'second_experience_start_date': DateInput(),
                    'second_experience_end_date': DateInput(),
                    'second_education_start_date': DateInput(),
                    'second_education_end_date': DateInput(),
                    }
        labels = {
            'education_start_date': 'From',
            'education_end_date': 'To',
            'experience_start_date': 'From',
            'experience_end_date': 'To',
            'second_education_start_date': 'From',
            'second_education_end_date': 'To',
            'second_experience_start_date': 'From',
            'second_experience_end_date': 'To',
            'url_url': '',
            'second_url_url': ''
        }

    def __init__(self, *args, **kwargs):
        name = kwargs.pop('name', None)
        email = kwargs.pop('email', None)
        super().__init__(*args, **kwargs)

        if name:
            self.fields['name'].initial = name
        if email:
            self.fields['email'].initial = email

        self.fields['professional_title'].widget.attrs['placeholder'] = 'eg. Web Developer'
        self.fields['location'].widget.attrs['placeholder'] = 'eg. Tallinn'
        self.fields['url_name'].widget.attrs['placeholder'] = 'Name'
        self.fields['url_url'].widget.attrs['placeholder'] = 'http://'
        self.fields['url_url'].widget.attrs['class'] = 'search-field'

        self.fields['second_url_name'].widget.attrs['placeholder'] = 'Name'
        self.fields['second_url_url'].widget.attrs['placeholder'] = 'http://'
        self.fields['second_url_url'].widget.attrs['class'] = 'search-field'

        self.fields['education_school_name'].widget.attrs['placeholder'] = 'School Name'
        self.fields['education_notes'].widget.attrs['placeholder'] = 'Notes (optional)'
        self.fields['second_education_school_name'].widget.attrs['placeholder'] = 'School Name'
        self.fields['second_education_notes'].widget.attrs['placeholder'] = 'Notes (optional)'

        self.fields['experience_employer'].widget.attrs['placeholder'] = 'Employer'
        self.fields['experience_job_title'].widget.attrs['placeholder'] = 'Job Title'
        self.fields['experience_notes'].widget.attrs['placeholder'] = 'Notes (optional)'

        self.fields['second_experience_employer'].widget.attrs['placeholder'] = 'Employer'
        self.fields['second_experience_job_title'].widget.attrs['placeholder'] = 'Job Title'
        self.fields['second_experience_notes'].widget.attrs['placeholder'] = 'Notes (optional)'


#    def save(self, *args, **kwargs):

candidate/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.urls import resolve

from jobposts import utils

from jobposts import models as job_models
from . import models


class JobBookmarkView(LoginRequiredMixin, View):
    lookup = 'id'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(job_models.Job, pk=self.kwargs.get(self.lookup))
    
    def get(self, request, id=None, *args, **kwargs):
        is_bookmarked = models.Bookmark.objects.find_is_bookmarked(self.get_object(), request.user)

        if is_bookmarked.exists():
            messages.error("Post has already been bookmarked")
            return redirect('jobposts:job-list')
        
        else:
            is_unbookmarked = models.UnBookmark.objects.find_is_unbookmarked(self.get_object(), request.user)

            if is_unbookmarked.exists():
                is_unbookmarked.delete()
                models.Bookmark.objects.create_bookmark(self.get_object(), request.user)
                messages.success(request, 'Job post has been bookmarked')
                prev_link = request.META.get('HTTP_REFERER')
                prev_link_last = prev_link.split('/')[-1]
                if utils.has_numbers_and_word('job', prev_link, prev_link_last):
                    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
                else:
                    messages.success(request, 'Job post has been bookmarked')
                    return redirect('jobposts:job-list')
            
            else:
                models.Bookmark.objects.create_bookmark(self.get_object(), request.user)
                messages.success(request, 'Job post has been bookmarked')
                return redirect('jobposts:job-list')


class JobUnbookmarkView(LoginRequiredMixin, View):
    lookup = 'id'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(job_models.Job, pk=self.kwargs.get(self.lookup))
    
    def get(self, request, id=None, *args, **kwargs):
        is_unbookmarked = models.UnBookmark.objects.find_is_unbookmarked(self.get_object(), request.user)
    
        if is_unbookmarked.exists():
            messages.error(request, "Post has already been unbookmarked")
            return redirect('jobposts:job-list')
        
        else:
            is_bookmarked = models.Bookmark.objects.find_is_bookmarked(self.get_object(), request.user)

            if is_bookmarked.exists():
                is_bookmarked.delete()
                models.UnBookmark.objects.delete_bookmark(self.get_object(), request.user)
                messages.success(request, 'Job post has been unbookmarked')
                if request.META.get('HTTP_REFERER'):
                    prev_link = request.META.get('HTTP_REFERER')
                    prev_link_last = prev_link.split('/')[-1]
                    if 'profile' in request.META.get('HTTP_REFERER') or utils.has_numbers_and_word('job', prev_link, prev_link_last):
                        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
                    else:
                        messages.success(request, 'Job post has been unbookmarked')
                        return redirect('jobposts:job-list')

            
            else:
                models.UnBookmark.objects.delete_bookmark(self.get_object(), request.user)
                messages.success(request, 'Job post has been unbookmarked')
                if request.META.get('HTTP_REFERER'):
                    prev_link = request.META.get('HTTP_REFERER')
                    prev_link_last = prev_link.split('/')[-1]
                    if 'profile' in request.META.get('HTTP_REFERER') or utils.has_numbers_and_word('job', prev_link, prev_link_last):
                        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
                    else:
                        return redirect('jobposts:job-list')
    

templates/candidate/add-resume.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}| Add Resume {% endblock title %}

{% block content %}


<!-- Titlebar
================================================== -->
<div id="titlebar" class="single submit-page">
	<div class="container">

		<div class="sixteen columns">
			<h2><i class="fa fa-plus-circle"></i> Add Resume</h2>
		</div>

	</div>
</div>


<!-- Content
================================================== -->
<div class="container">
	
	<!-- Submit Page -->
	<div class="sixteen columns">
		<div class="submit-page">
       	<form method="POST" action="{% url 'accounts:add-resume' %}" enctype="multipart/form-data" id="showall">
            {% csrf_token %}

			<!-- Email -->
			<div class="form">
				<h5>Your Name</h5>
				{{ form.name }}
			</div>

			<!-- Email -->
			<div class="form">
				<h5>Your Email</h5>
				{{ form.email }}
			</div>

			<!-- Title -->
			<div class="form">
				<h5>Professional Title</h5>
				{{ form.professional_title }}
			</div>

			<!-- Location -->
			<div class="form">
				<h5>Location</h5>
				{{ form.location }}
			</div>

			<!-- Description -->
			<div class="form">
				<h5>Resume Content</h5>
				{{ form.description }}
			</div>

			<div style="padding-top:10px; border-top: 1px solid #bbb;"></div>
			<!-- URls -->
			<h5>URL(s) <span>(socials, optional)</span></h5>

			<button id="close_url" type="button" style="float: right; background: #0304044d; font-size: 10px; padding: 7px;">X</button>
			<button type="button" id="add-url-button">+ Add socials/urls</button>
		
			<!-- urls fields will show on click -->

			<div style="margin-bottom:50px;"></div>
			<p class="note">Optionally provide links to any of your websites or social network profiles.</p>
			<div style="padding-top:10px; border-top: 1px solid #bbb;"></div>

			<!-- Education -->
			<h5>Education <span>(optional)</span></h5>
			<button id="close_education" type="button" style="float: right; background: #0304044d; font-size: 10px; padding: 7px;">X</button>

			<button type="button" id="education-button">+ Add education</button>
			<div style="margin-bottom:10px;"></div>

			<!-- Education div will show -->

			<div style="margin-bottom:50px;"></div>
			<div style="padding-top:10px; border-top: 1px solid #bbb;"></div>


			<!-- Experience  -->
			<h5>Experience <span>(optional)</span></h5>

			<button id="close_experience" type="button" style="float: right; background: #0304044d; font-size: 10px; padding: 7px;">X</button>
			<button type="button" id="experience-button">+ Add experience</button>

			<!-- Experience div is showing on click -->

			<div style="margin-bottom:50px;"></div>

			<div style="padding-top:10px; border-top: 1px solid #bbb;"></div>
			<button type="submit" class="button big margin-top-5">Add Resume <i class="fa fa-arrow-circle-right"></i></button>

		</form>
		</div>
	</div>

</div>


<script>

$(document).ready(function() {
        var domExperience = $(`<div style="margin-top:10px;"></div>
			<div id="experience">
				<h2>First Experience</h2>
				{{ form.experience_employer }}
				<div style="margin-bottom:5px;"></div>
				{{ form.experience_job_title }}
				<div style="margin-bottom:10px;"></div>
				{{ form.experience_start_date | as_crispy_field }}
				{{ form.experience_end_date | as_crispy_field }}
				<h6>Notes/Description</h6>
				{{ form.experience_notes }}
			</div>
			`);
		
		var domExperience2 = $(`<div style="margin-top:10px;"></div>
			<div id="second_experience">
				<h2>Second Experience</h2>
				{{ form.second_experience_employer }}
				<div style="margin-bottom:5px;"></div>
				{{ form.second_experience_job_title }}
				<div style="margin-bottom:10px;"></div>
				{{ form.second_experience_start_date | as_crispy_field }}
				{{ form.second_experience_end_date | as_crispy_field }}
				<h6>Notes/Description</h6>
				{{ form.second_experience_notes }}
			</div>
				<div style="margin-bottom:50px;"></div>
			`);
        
        var domElement = $(`<div style="margin-top:10px;"></div>
				<div id="education">
					<h2>First Education</h2>
					{{ form.education_school_name }}
					<div style="margin-bottom:10px;"></div>
					<h6>Education level</h6>
					{{ form.education_education_major }}
					<div style="margin-bottom: 10px;"></div>
					{{ form.education_start_date | as_crispy_field }}
					{{ form.education_end_date | as_crispy_field }}
					<h6>Notes/Description</h6>
					{{ form.education_notes }}
				</div>
				<div style="margin-bottom:50px;"></div>
			`);

		var domElement2 = $(`<div style="margin-top:10px;"></div>
				<div id="second_education">
					<h2>Second Education</h2>	
					{{ form.second_education_school_name }}
					<div style="margin-bottom:10px;"></div>
					<h6>Education level</h6>
					{{ form.second_education_education_major }}
					<div style="margin-bottom: 10px;"></div>
					{{ form.second_education_start_date | as_crispy_field }}
					{{ form.second_education_end_date | as_crispy_field }}
					<h6>Notes/Description</h6>
					{{ form.second_education_notes }}
					<div style="margin-bottom:50px;"></div>
				</div>
			`);
        
        var domUrl = $(`<div style="margin-top:10px;"></div>
				<div id="urls">
					<h2>First URL</h2>
					{{ form.url_name }}
					<div style="margin-bottom:5px;"></div>
					{{ form.url_url | as_crispy_field }}
				</div>
			`);
		
		var domUrl2 = $(`<div style="margin-top:10px;"></div>
				<div id="second_urls">
					<h2>Second URL</h2>
					{{ form.second_url_name }}
					<div style="margin-bottom:5px;"></div>
					{{ form.second_url_url | as_crispy_field }}
					<div style="margin-bottom:50px;"></div>
				</div>
			`);
		
		var expButtonCount = 0;
		var edButtonCount = 0;
		var urlButtonCount = 0;

		$("button[id='experience-button']").click(function(e) {
			expButtonCount++;
			if (expButtonCount > 2){
				expButtonCount = 2;
			} else if (expButtonCount < 0) {
				expButtonCount = 0
			}
			if (expButtonCount == 1) {
				$(this).after(domExperience);
				e.preventDefault();
			} else if (expButtonCount == 2) {
				$(this).after(domExperience2);
				e.preventDefault();
			}
		});

        $("button[id='education-button']").click(function(e) {
			edButtonCount++;
			if (edButtonCount > 2) {
			    edButtonCount = 2;
			} else if (edButtonCount < 0) {
				edButtonCount = 0;
			}
			if (edButtonCount == 1) {
				$(this).after(domElement);
				e.preventDefault();
			} else if (edButtonCount == 2) {
				$(this).after(domElement2);
				e.preventDefault();
			}
        });

        $("button[id='add-url-button']").click(function(e) { 
			urlButtonCount++;
			if (urlButtonCount > 2) {
				urlButtonCount = 2;
			} else if (urlButtonCount < 0) {
				urlButtonCount = 0;
			}
			if (urlButtonCount == 1){
				$(this).after(domUrl);
				e.preventDefault();
			} else if (urlButtonCount == 2) {
				$(this).after(domUrl2);
				e.preventDefault();
			}
        });

        $("#showall").submit(function() { 
            $("button[id='experience-button']").after(domExperience);
            $("button[id='education-button']").after(domElement);
            $("button[id='add-url-button']").after(domUrl);
			$("button[id='experience-button']").after(domExperience2);
			$("button[id='education-button']").after(domElement2);
			$("button[id='add-url-button']").after(domUrl2);
        });

		$("button[id='close_education']").click(function () {
			if (edButtonCount == 1) {
				$("#education").remove();
				edButtonCount--;
			} else if (edButtonCount == 2) {
				$("#second_education").remove();
				edButtonCount--;
			}
		})

		$("button[id='close_experience']").click(function () {
			if (expButtonCount == 1) {
				$("#experience").remove();
				expButtonCount--;
			} else if (expButtonCount == 2) {
				$("#second_experience").remove();
				expButtonCount--;
			}
		})

		$("button[id='close_url']").click(function () {
			if (urlButtonCount == 1) {
				$("#urls").remove();
				urlButtonCount--;
			} else if (urlButtonCount == 2) {
				$("#second_urls").remove();
				urlButtonCount--;
			}
		})
	});

</script>

{% endblock %}
 

templates/candidate/confirm-resume-delete.html
{% extends "base.html" %}

{% block title %}| Delete confirmation {% endblock title %}

{% block content %}

    <div class="container-own">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Hey {{ request.user.username }}!</legend>
                <h2>Are you sure you want to delete this resume?
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'accounts:resume' object.id %}">Cancel</a>
            </div>
            
        </form>
    </div>
    <div style="margin-bottom:300px;"></div>

{% endblock content %}

templates/candidate/resume.html
{% extends 'base.html' %}

{% block title %}| Resume {% endblock title %}
{% load employer_tags %}

{% block content %}

{% is_resume_bookmarked resume.id request.user as is_resume_booked %}

<!-- Titlebar
================================================== -->
<div id="titlebar" class="resume">
	<div class="container-own">
		<div class="ten columns">
			<div class="resume-titlebar">
				<img src="{{ resume.owner.candidateprofile.image.url }}" alt="">
				<div class="resumes-list-content">
					<h4>{{ resume.name }} <span>{{ resume.professional_title }}</span></h4>
					{% if resume.owner.candidateprofile.image.url %}
						<span class="icons"><i class="fa fa-map-marker"></i> {{ resume.owner.candidateprofile.city }}</span>
					{% endif %}
					<span class="icons"><a href="#"><i class="fa fa-link"></i> Website</a></span>
					<span class="icons"><a href="mailto:{{ resume.owner.email }}"><i class="fa fa-envelope"></i> {{ resume.email }}</a></span>
					<div class="skills">
						{% for ski in resume.owner.candidateprofile.skills.all %}
							<span><img src="{{ ski.category_thumb.url }}" style="width:20px; height: 25px; float:none; padding-bottom: 6px;"><p style="display:inline; text-align:center;"> {{ ski }}</p></span>
						{% endfor %}
					</div>
					<div class="clearfix"></div>

				</div>
			</div>
		</div>

		<div class="six columns">
			<div class="two-buttons">
				{% if request.user.id != resume.owner.id %}
					<a href="#small-dialog" class="popup-with-zoom-anim button"><i class="fa fa-envelope"></i> Send Message</a>

					<div id="small-dialog" class="zoom-anim-dialog mfp-hide apply-popup">
						<div class="small-dialog-headline">
							<h2>Send Message to {{ resume.owner.first_name }} {{ resume.owner.last_name }}</h2>
						</div>

						<div class="small-dialog-content">
							<form action="#" method="get" >
								<input type="text" placeholder="Full Name" value=""/>
								<input type="text" placeholder="Email Address" value=""/>
								<textarea placeholder="Message"></textarea>

								<button class="send">Send Message</button>
							</form>
						</div>
						
					</div>
				{% endif %}

				{% if user.is_employer %}

					{% if is_resume_booked %}	
						<a href="{{ resume.get_unbookmark_url }}" class="button dark"><i class="fa fa-star"></i> Delete Bookmark</a>
					{% else %}
						<a href="{{ resume.get_bookmark_url }}" class="button dark"><i class="fa fa-star-o"></i> Bookmark This Resume</a>
					{% endif %}

				{% endif %}

				{% if request.user.id == resume.owner.id %}
				<div class="dropdown" style="float:right; ">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:#8B8D7E;">
							Update Resume
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item" href="{% url 'accounts:resume-update' resume.id %}">Update</a>
							<a class="dropdown-item" href="{% url 'accounts:resume-delete' resume.id %}">Delete</a>
						</div>
				</div>
				{% endif %}

			</div>
		</div>

	</div>
</div>


<!-- Content
================================================== -->
<div class="container-own">
	<!-- Recent Jobs -->
	<div class="eight columns">
	<div class="padding-right">

		<h3 class="margin-bottom-15">About Me</h3>
			
		{{ resume.description|safe }}

	</div>
	</div>


	<!-- Widgets -->
	<div class="eight columns">

		<h3 class="margin-bottom-20">Education</h3>

		<!-- Resume Table -->
		<dl class="resume-table">

			{% if resume.second_education_school_name %}
				<dt>
					<span>Major: {{ resume.second_education_education_major}}</span>
					<strong><i class="fa fa-map-marker"></i> {{ resume.second_education_school_name }}</strong>
					<small class="date">{{ resume.second_education_start_date|date:"M Y" }} - {{ resume.second_education_end_date|date:"M Y" }}</small>
				</dt>
				<dd>
					<p>{{ resume.second_education_notes }}</p>
				</dd>
			{% endif %}

			{% if resume.education_school_name %}
				<dt>
					<span>Major: {{ resume.education_education_major }}</span>
					<strong><i class="fa fa-map-marker"></i> {{ resume.education_school_name }}</strong>
					<small class="date">{{ resume.education_start_date|date:"M Y" }} - {{ resume.education_end_date|date:"M Y" }}</small>
				</dt>
				<dd>
					<p>{{ resume.education_notes }}</p>
				</dd>
			{% else %}
			<p>User did not provide any information about its education for this particular resume</p>
			{% endif %}

		</dl>

		<h3 class="margin-bottom-20">Experience</h3>

		<!-- Resume Table -->
		<dl class="resume-table">
			{% if resume.second_experience_job_title %}
				<dt>
					<strong>{{ resume.second_experience_job_title }}</strong>
					<span class="icons"><i class="fa fa-map-marker"></i> {{ resume.second_experience_employer }}</span><br/>
					<small class="date">{{ resume.second_experience_start_date|date:"M Y" }} - {{ resume.second_experience_end_date|date:"M Y" }}</small>
				</dt>
				<dd>
					<p>{{ resume.second_experience_notes }}</p>
				</dd>
			{% endif %}

			{% if resume.experience_job_title %}
				<dt>
					<strong>{{ resume.experience_job_title }}</strong>
					<span class="icons"><i class="fa fa-map-marker"></i> {{ resume.experience_employer }}</span><br/>
					<small class="date">{{ resume.experience_start_date|date:"M Y" }} - {{ resume.experience_end_date|date:"M Y" }}</small>
				</dt>
				<dd>
					<p>{{ resume.experience_notes }}</p>
				</dd>
				{% else %}
				<p>User did not provide any information about its experience for this particular resume</p>
			{% endif %}

		</dl>

	</div>

</div>

{% endblock content %}